### ISSUE TITLE
Issue with the lamda function when training with coustom dataset on mask-rcnn

### ISSUE THREAD

**Issue by kumbarisagar3011** [AarohiSingla/Mask-R-CNN-using-Tensorflow2#3]
Traceback (most recent call last):
  File "D:\Local Disk E\Project-mask-rcnn\Mask_RCNN\custom.py", line 238, in <module>
    model = modellib.MaskRCNN(mode="training", config=config,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Local Disk E\Project-mask-rcnn\Mask_RCNN\mrcnn\model.py", line 1838, in __init__
    self.keras_model = self.build(mode=mode, config=config)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Local Disk E\Project-mask-rcnn\Mask_RCNN\mrcnn\model.py", line 1876, in build
    gt_boxes = KL.Lambda(lambda x: norm_boxes_graph(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Local Disk E\Project-mask-rcnn\mask-rcnn\Lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in erroler
    raise e.with_traceback(filtered_tb) from None
  File "d:\Local Disk E\Project-mask-rcnn\mask-rcnn\Lib\site-packages\keras\src\layers\core\lambda_layer.py", line 95, in cooutput_shape
    raise NotImplementedError(
NotImplementedError: Exception encountered when calling Lambda.call().

We could not automatically infer the shape of the Lambda's output. Please specify the `output_shape` argument for this Lambda layer.

Arguments received by Lambda.call():
  • args=('<KerasTensor shape=(None, None, 4), dtype=float32, sparse=None, name=input_gt_boxes>',)
  • kwargs={'mask': 'None'}
  
  
  
  what to do to get rid of this error?

**Comment by TXWISSRX** [comment]
me too
still not solved
